In [1]:
import numpy as np

In [ ]:
######## 1: empty#####

In [2]:
w=np.empty(6)

In [3]:
w

array([5.26125257e-315, 0.00000000e+000, 7.68290848e+170, 4.88041047e+252,
       1.33510222e+160, 8.82883579e+199])

In [5]:
w=np.empty(6).reshape(3,2)

In [6]:
w

array([[5.26125257e-315, 0.00000000e+000],
       [7.68290848e+170, 4.88041047e+252],
       [1.33510222e+160, 8.82883579e+199]])

In [7]:
w=np.empty(6).reshape(2,3)

In [8]:
w

array([[5.26125257e-315, 0.00000000e+000, 7.68290848e+170],
       [4.88041047e+252, 1.33510222e+160, 8.82883579e+199]])

In [11]:
p=np.empty([3,2],dtype=int)

In [12]:
p

array([[         1064889376,                   0],
       [7163382526550814307, 8387194742780223790],
       [7002643775149533554, 7598263499762854256]])

In [ ]:
#######2: arange ###########

In [13]:
r=np.arange(2,21,2).reshape(5,2)

In [14]:
r

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [15]:
########## 3: zero ##########

In [17]:
q=np.zeros(6)

In [18]:
q

array([0., 0., 0., 0., 0., 0.])

In [19]:
r=np.zeros([5,4],dtype=int).reshape(3,2)

ValueError: cannot reshape array of size 20 into shape (3,2)

In [20]:
r=np.zeros(6,dtype=int).reshape(3,2)

In [21]:
r

array([[0, 0],
       [0, 0],
       [0, 0]])

In [22]:
########## 4: one #########

In [23]:
m=np.ones([4,5],dtype=int)

In [24]:
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
########### eye #######

In [27]:
l=np.eye(1)

In [28]:
l

array([[1.]])

In [29]:
o=np.eye(2)

In [30]:
o

array([[1., 0.],
       [0., 1.]])

In [31]:
q=np.eye(3)

In [32]:
q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
######## linkspace #######

In [35]:
k=np.linspace(0,1,100)

In [36]:
k

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [37]:
n=np.linspace(10,20,5)

In [38]:
n

array([10. , 12.5, 15. , 17.5, 20. ])

In [43]:
x=np.zeros([10,10])

In [44]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
x.shape[1]

10

In [47]:
le=x.shape[1]

In [48]:
le

10

In [49]:
for i in range(le):
  x[i]=i

In [50]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])