In [1]:
import numpy as np

In [2]:
a=np.arange(1,7)

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.shape

(6,)

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a.ndim

1

In [7]:
a[3]

np.int64(4)

In [8]:
a[4]

np.int64(5)

In [9]:
a[]

SyntaxError: invalid syntax (ipython-input-1145722274.py, line 1)

In [17]:
a[2:5:1]

array([3, 4, 5])

In [10]:
z=np.arange(1,21).reshape(5,4)

In [11]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [12]:
z[1]

array([5, 6, 7, 8])

In [14]:
z[0: :3]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [16]:
z[2:5:1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
z[1:4:2,2: :1]

array([[ 7,  8],
       [15, 16]])

In [41]:
z[0:4:1,1:4:1]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [42]:
z[2: :-1,3: :-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [44]:
z[4:1:-1,3:2:-1]

array([[20],
       [16],
       [12]])

In [45]:
########topic 2: broadcasting in an array##########

m=np.arange(1,7)

In [46]:
m

array([1, 2, 3, 4, 5, 6])

In [47]:
m[2]=55

In [48]:
m

array([ 1,  2, 55,  4,  5,  6])

In [49]:
m[ : :2]=15

In [50]:
m

array([15,  2, 15,  4, 15,  6])

In [51]:
m[1: :2]=0

In [52]:
m

array([15,  0, 15,  0, 15,  0])

In [53]:
n=np.arange(1,21).reshape(4,5)

In [54]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
n[: :4]=55

In [56]:
n

array([[55, 55, 55, 55, 55],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
n[: :1,3:4:1]=0.25

In [58]:
n

array([[55, 55, 55,  0, 55],
       [ 6,  7,  8,  0, 10],
       [11, 12, 13,  0, 15],
       [16, 17, 18,  0, 20]])