In [1]:
import numpy as np

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape=(3,2)

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a

In [ ]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
b.shape

(4, 3)

In [ ]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
######### functions using numpy ###

x=np.arange(1,7)

In [ ]:
x

array([1, 2, 3, 4, 5, 6])

In [ ]:
x.shape

(6,)

In [ ]:
x=np.arange(1,7).reshape(2,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y=np.arange(7,13).reshape(2,3)

In [ ]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
z=np.concatenate(x,y)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
z=np.concatenate((x,y))

In [ ]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m=np.hstack((x,y))

In [ ]:
m

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
q=np.array([1,2,3,4,5,6])
np.vstack((q))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
q=np.array([1,2,3,4,5,6])
r=np.array([7,8,9,10,11,13])
s=np.vstack((q,r))

In [ ]:
s

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 13]])

In [ ]:
ap=np.arange(1,7)

In [ ]:
ap

array([1, 2, 3, 4, 5, 6])

In [ ]:
ap=np.append(ap,[7,8,9])

In [ ]:
ap

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mn=np.array([2,3,4,5])

In [ ]:
mn=np.insert(mn,0,1)

In [ ]:
mn

array([1, 2, 3, 4, 5])

In [ ]:
mn=np.insert(mn,3,7)

In [ ]:
mn

array([1, 2, 3, 7, 4, 5])

In [ ]:
mn=np.delete(mn,[0,2,4])

In [ ]:
mn

array([2, 7, 5])